version: '3.8'

services:
  turbo:
    build: app
    container_name: turbo
    env_file: .env
    ports:
      - "80:3000"
  extractor:
    build: app/apps/extractor
    container_name: extractor
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: