version: '3.8'

services:
  turbo:
    build: app
    container_name: turbo
    ports:
      - '3000:3000'
    networks:
      - internal
  extractor:
    build: app/apps/extractor
    container_name: extractor
    ports:
      - '5000:5000'
    networks:
      - internal
  ollama:
    build: app/apps/ollama
    container_name: ollama
    ports:
      - '80:80'
    networks:
      - internal

networks:
  internal:
    driver: bridge