import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import Menu from "../components/ui/menu";
import { AuthProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mimir",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  const user = true;

  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthProvider>

        {user ? (
            <>

            <div className="min-w-[15vw]">
              <Menu />
            </div>
            <div className="flex h-screen w-[85%] justify-center items-center">
              {children}
            </div>


            </>
          ) : (
            <>

            <div className="flex h-screen min-w-[100%] justify-center items-center">
                {children}
            </div>

            </>
          )}

      </AuthProvider>
      
      </body>
    </html>
  );
}
